FE9-2/workroot

src/app/components/button/default/BookmarkBtn.tsx, src/app/components/button/default/Button.tsx, src/app/components/button/default/CheckBtn.tsx, src/app/components/button/default/Chip.tsx, src/app/components/button/default/FloatingBtn.tsx, src/app/components/button/default/FrameRadioBtn.tsx, src/app/components/button/dropdown/DropdownListBtn.tsx, src/app/components/button/dropdown/FilterBtn.tsx, src/app/components/button/dropdown/InputDropdownBtn.tsx, src/app/components/button/dropdown/SortBtn.tsx, src/app/components/layout/Footer.tsx, src/app/error.tsx, src/app/not-found.tsx, src/app/stories/design-system/components/buttons/DropdownList.stories.tsx, src/app/stories/design-system/components/buttons/FilterBtn.stories.tsx, src/app/stories/design-system/components/buttons/InputDropdownBtn.stories.tsx, src/app/stories/design-system/components/buttons/SortBtn.stories.tsx, tailwind.config.ts
일단 하드코딩으로 이렇게 데이터를 넣었습니다. ⚠️ **_(추후에 수정 필요)_**
여기 데이터도 하드코딩이라 값은 ⚠️ **_(추후에 수정 필요)_**
=> design: DropdownListBtn, InputDropdownBtn UI 구현 완료

src/app/components/button/dropdown/FilterDropdown.tsx, src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx, src/app/components/input/dateTimeDaypicker/TimePickerInput.tsx
- 드롭다운 열었을때 버튼 위치가 이동하는 문제 해결 (absolute 추가)
- 드롭다운 크기가 안맞는 문제 해결
=> chore: 드롭다운 크기, 위치 수정

src/app/components/card/cardList/MyApplicationListItem.tsx, src/app/components/card/cardList/RecruitIcon.tsx, src/app/components/card/cardList/RecruitIconItem.tsx, src/app/components/card/cardList/RecruitListItem.tsx, src/app/components/pagination/Indicator.tsx, src/app/stories/design-system/components/card/cardList/RecruitIcon.stories.tsx, src/app/stories/design-system/components/card/cardList/RecruitListItem.stories.tsx, src/app/stories/design-system/components/pagination/Indicator.stories.tsx
> RecruitListItem
1. 슬라이더 네비게이션 버튼 관련 코드 제거
2. Indicator 컴포넌트 추가 및 연동
3. 이미지 인디케이터 위치 조정
> Indicator 컴포넌트에서:
1. 내부 상태 제거
2. Props로 currentPage와 onPageChange 추가
3. 클릭 이벤트 핸들링을 부모 컴포넌트로 위임
=> refactor: Card List 아이템 관련

src/app/(auth)/login/page.tsx, src/app/(auth)/signup/applicant/page.tsx, src/app/(auth)/signup/owner/page.tsx, src/app/(auth)/signup/page.tsx, src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx, src/app/(pages)/mypage/components/FilterBar/index.tsx, src/app/(pages)/mypage/components/sections/CommentsSection.tsx, src/app/(pages)/mypage/components/sections/PostsSection.tsx, src/app/(pages)/mypage/components/sections/ScrapsSection.tsx, src/app/components/layout/Header.tsx, src/app/components/modal/modals/confirm/CustomFormModal.tsx, src/app/stories/design-system/components/modal/confirm/CustomFormModal.stories.tsx, src/hooks/useAuth.ts, src/middleware.ts, src/types/modal.d.ts
1. 회원가입 페이지 분리 ("/signup/applicant", "/signup/owner")
2. useAuth 리팩토링
3. middleware 수정
4. CustomFormModal 추가(커스텀 confirm 모달)
=> refactor: 회원가입 페이지 분리 및 관련 리팩토링

.storybook/preview.tsx, src/app/stories/design-system/components/modal/form/ChangePasswordModal.stories.tsx
ChangePasswordModal 스토리북 에러를 수정했어요.
=> fix: ChangePasswordModal 스토리북 관련 버그 수정

src/app/api/(file)/resume/upload/route.ts, src/app/api/users/me/route.ts, src/app/components/input/file/ImageInput/ImageInputwithPlaceHolder.tsx, src/app/components/layout/Header.tsx, src/app/components/modal/modals/form/EditMyProfileModal.tsx, src/app/components/modal/modals/form/EditOwnerProfileModal.tsx, src/app/stories/design-system/components/input/picker/DatePicker.stories.tsx, src/hooks/useAuth.ts, src/hooks/useUser.ts, src/middleware.ts
1. user 정보 localStorage 대신 react query 활용
2. 빌드 에러 파일 수정
=> user 정보 localStorage 대신 react query 활용 등

src/app/(pages)/albaList/components/SearchSection.tsx, src/app/(pages)/albaList/page.tsx, src/app/components/input/text/SearchInput.tsx, src/app/stories/design-system/components/SearchSection.tsx, src/app/stories/design-system/components/input/text/SearchInput.stories.tsx, src/app/stories/design-system/components/layout/Header.tsx, src/app/stories/design-system/pages/albaList/page.stories.tsx, src/app/stories/design-system/pages/albaList/page.tsx
1. 알바 리스트 > 검색 섹션 추가
2. 스토리북 알바리스트 > 검색 섹션 추가
3. 사장님 권한 체크 및 폼 만들기 버튼 추가
=> feat: 검색 섹션 추가 및 스토리북 반영

src/app/(auth)/login/page.tsx, src/app/(pages)/(albaform)/layout.tsx, src/app/(pages)/alba-list/page.tsx, src/app/(pages)/alba-talk/[albatalkId]/sections/PostDetailSection.tsx, src/app/(pages)/alba-talk/page.tsx, src/app/(pages)/mypage/components/FilterBar/SortSection.tsx, src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx, src/app/(pages)/mypage/components/FilterBar/constants.ts, src/app/(pages)/mypage/page.tsx, src/app/components/button/default/Button.tsx, src/app/components/button/default/LinkBtn.tsx, src/app/components/card/board/BoardComment.tsx, src/app/components/card/board/CardBoard.tsx, src/app/components/card/board/Comment.tsx, src/app/components/card/cardList/AlbaListItem.tsx, src/app/components/layout/Header.tsx, src/app/components/layout/forms/SearchSection.tsx, src/app/components/layout/forms/SortSection.tsx, src/app/components/layout/posts/SortSection.tsx, src/app/components/modal/modals/confirm/CustomFormModal.tsx, src/hooks/queries/post/comment/useAddComment.ts, src/hooks/queries/post/comment/useDeleteComment.ts, src/hooks/queries/post/comment/useEditComment.ts, src/hooks/queries/post/useAddPost.ts, src/hooks/queries/post/useDeletePost.ts, src/hooks/queries/post/useEditPost.ts
1. 마이페이지 > 스크랩 메뉴 제거
2. 워크폼 리스트 아이템 케밥 메뉴 제거
1. 워크채널  > 리스트 아이템 클릭시 로그인 유도 모달
2. 워크톡 > 리스트 아이템 클릭시 로그인 유도 모달
- closeModal 사용해서 코드 단순화
=> 사장님 관련 마이페이지 스크랩 제거 등

src/app/components/button/default/LinkBtn.tsx, src/app/components/layout/Header.tsx
=> design: 사이드바 수정

src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx, src/app/(pages)/my-workform/(role)/applicant/page.tsx, src/app/(pages)/my-workform/(role)/owner/page.tsx, src/app/(pages)/mypage/components/sections/CommentsSection.tsx, src/app/(pages)/mypage/components/sections/PostsSection.tsx, src/app/(pages)/work-list/page.tsx, src/app/(pages)/work-talk/page.tsx, src/app/components/card/board/Comment.tsx, src/app/components/layout/forms/SearchSection.tsx, src/app/components/loading-spinner/NoApplySpinner.tsx, src/app/components/loading-spinner/SearchSpinner.tsx
- 경로별 검색창 place holder 수정
- 워크폼 삭제 시 리스트 쿼리 무효화 추가
- 불필요한 min-h-screen 삭제 (빈 페이지에서도 스크롤바 생기게 됩니다)
- 댓글 간격 추가
=> chore: 자잘한 수정

src/app/(pages)/work-talk/[talkId]/page.tsx
=> fix: 워크톡 > 상세 id 관련 버그 수정

src/app/(auth)/login/page.tsx, src/app/(auth)/signup/applicant/page.tsx, src/app/(auth)/signup/owner/page.tsx, src/app/(pages)/(workform)/work/[formId]/edit/page.tsx, src/app/components/input/text/AuthInput.tsx, src/types/textInput.d.ts
1. 로그인, 회원가입 AuthInput 추가 및 사용
2. 워크폼 상세 페이지 수정 후 react query 캐시 무효화 수정
- 로컬 스토리지 데이터 삭제
- 쿼리 무효화
- 성공 메시지 표시
- 페이지 이동
순서로 실행되어 쿼리 무효화가 제대로 이루어집니다.
그리고, 쿼리 무효화가 완료되기를 기다리기 위해 await를 사용합니다.
=> refactor: 로그인, 회원가입 AuthInput 추가 및 사용 등

src/app/(pages)/my-workform/(role)/applicant/page.tsx, src/app/(pages)/my-workform/(role)/owner/page.tsx, src/app/(pages)/mypage/components/sections/CommentsSection.tsx, src/app/(pages)/mypage/components/sections/PostsSection.tsx, src/app/(pages)/mypage/components/sections/ScrapsSection.tsx, src/app/(pages)/work-list/page.tsx, src/app/(pages)/work-talk/page.tsx, src/app/components/button/default/ScrollTopButton.tsx
=> feat: 무한스크롤 있는 페이지에 최상단으로 스크롤 되는 버튼 추가

src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx, src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx, src/app/(pages)/(workform)/work/[formId]/edit/page.tsx, src/hooks/queries/user/me/useImageUpload.ts, src/hooks/queries/user/me/useUpdateProfile.ts
(동일한 로직이 있는 페이지에 수정사항 적용했습니다) 
- 불필요한 상태 삭제
수정 전 : setState (A) -> useEffect (A에 의해 B 변경) -> B 값 업데이트
수정 후 : B <= A 직접 변경  (state, useEffect 제거) 
- 이미지 업로드 시 로딩 스피너 추가
- 달력 NaN 표기 삭제
=> chore : 추가 수정

src/app/metadata.ts, src/app/viewport.ts
1. 페이스북 app_id 인식 못하는 문제 수정
2. metadata.ts 에서 viewport 설정 제거, viewport.ts 에서 관리
=> 페이스북 app_id 관련 수정 등

src/app/api/forms/[formId]/route.ts, src/app/layout.tsx, src/app/metadata.ts
>  페이스북 app_id 는 Metadata 속성에 property 를 지원하지 않기에 직접 설정
> 비회원 워크폼 상세 페이지 접근시 누락된 코드 다시 적용
=> 페이스북 SEO 관련 수정

src/app/(pages)/(workform)/work/[formId]/edit/page.tsx, src/app/components/mouseTrail/CustomCursor.tsx, src/app/components/mouseTrail/MouseTrail.tsx
- 데이터피커 달력 열렸을때 마우스 커서 위치 버그 발생해 수정했습니다
- 워크폼 수정 페이지에서 버튼이 제대로 활성화되지않아 수정했습니다
=> chore: 커서 수정 / 워크폼 수정 페이지 수정

package-lock.json, package.json, public/sitemap.xml, src/app/clientLayout.tsx, src/app/components/layout/ChannelTalk.tsx
=> ChannelTalk 연동 추가

src/app/(auth)/signup/page.tsx, src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx, src/app/components/modal/modals/apply/MyApplicationModal.tsx
=> fix: 빌드 프리티어 에러 수정

src/utils/shareToKakao.ts
> shareToKakao
logo.svg 를 logo.png 로 변경
=> logo.svg 를 logo.png 로 변경
